//go:build ignore
// +build ignore

package main

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

func main() {
	// 尝试从 git tag 获取版本号
	version := getVersionFromGit()

	// 生成 app_build/version.go 文件
	content := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.

package app_build

const (
	// ShortVersion 短版本号，由 git tag 生成
	ShortVersion = "%s"
)
`, version)

	// 确保文件生成到 app_build 目录
	versionPath := "app_build/version.go"
	if err := os.WriteFile(versionPath, []byte(content), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing version.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with version: %s\n", versionPath, version)
}

func getVersionFromGit() string {
	// 1. 检查是否有 git tag
	cmd := exec.Command("git", "describe", "--tags", "--abbrev=0", "--always")
	output, err := cmd.Output()
	if err == nil {
		version := strings.TrimSpace(string(output))
		// 移除 v 前缀（如果有）
		version = strings.TrimPrefix(version, "v")
		// 验证是否为有效的语义化版本
		if isValidVersion(version) {
			return version
		}
	}

	// 2. 如果没有 git tag，获取 commit hash
	cmd = exec.Command("git", "rev-parse", "--short", "HEAD")
	output, err = cmd.Output()
	if err == nil {
		commit := strings.TrimSpace(string(output))
		return "0.0.0-" + commit
	}

	// 3. 如果没有 git，返回默认版本
	return "0.0.0-dev"
}

func isValidVersion(version string) bool {
	// 简单检查版本号格式: x.y.z 或 x.y.z-rc1 等
	parts := strings.Split(version, "-")
	if len(parts) > 2 {
		return false
	}

	versionParts := strings.Split(parts[0], ".")
	if len(versionParts) < 2 || len(versionParts) > 3 {
		return false
	}

	for _, part := range versionParts {
		if part == "" {
			return false
		}
		for _, c := range part {
			if c < '0' || c > '9' {
				return false
			}
		}
	}

	return true
}
